### ISSUE TITLE
Doesn't react to start key

### ISSUE THREAD

**Issue by FreeyaAesir** [xdsai/aafish#1]
I press the key to start and it doesnt react. END works and closes the program but ` doesn,t. Tried changing the key in code and still no reaction

**Comment by xdsai** [comment]
are you sure the capture zone is setup correct? it is likely started, just that it doesnt actually detect anything

**Comment by FreeyaAesir** [comment]
I was using default settings with default game UI

**Comment by FreeyaAesir** [comment]
At first I had problems installing requirements because win32gui is no longer supported, it started working after installing pywin32 and then I ran into this problem

**Comment by FreeyaAesir** [comment]
`Traceback (most recent call last):
  File "C:\Users\kamil\Documents\aafish-master\fish.py", line 123, in <module>
    point = find_image_location(screenshot, template_image)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kamil\Documents\aafish-master\fish.py", line 24, in find_image_location
    result = cv2.matchTemplate(main_image_gray, template_image_gray, method)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'`

**Comment by xdsai** [comment]
Whats the res of the monitor you're running the game on?
